### ISSUE TITLE
Can't run example code on new SvelteKit project

### ISSUE THREAD

**Issue by danielgraziani91** [Hejtmus/svelte-fullpage#61]
Hi!
Started a new project right now, pasted [the example code](https://github.com/Hejtmus/svelte-fullpage#example-code) code and all I see is

![this](https://github.com/Hejtmus/svelte-fullpage/assets/59689758/bd101535-d191-4172-b27f-f0b79cd92c9b)

What am I doing wrong?

**Comment by Hejtmus** [comment]
Hey @danielgraziani91,

thanks for asking. `<Fullpage>` component is set to inherit it's parent height, so if you don't set your parents component height, entire height setting of this library fails. This behavior is intentional, as sometimes it is useful to use `<Fullpage>` as slider, or because of footer that is not positioned fixed. I tried replicating your code and fixing it, here you can see height set:

![image](https://github.com/Hejtmus/svelte-fullpage/assets/34794791/3cdd8e0a-f823-4132-a0d2-77bf0b13dff2)

If you don't like this behavior, you can propose solution or at least propose adding it to docs. I would like to know opinion of user of this library (except me, because I also develop it, my opinion is distorted), please let me know.

Best regards,
Filip.

**Comment by danielgraziani91** [comment]
I thought of the parent height after shutting down the pc :D sorry for the silly question. I'm trying the package right now!

**Comment by Hejtmus** [comment]
It's ok, if you asked this question, that means somebody else asked this question. Do you think, that I should improve docs?

**Comment by danielgraziani91** [comment]
Yes, I would make it clear ;) I also [opened a PR](https://github.com/Hejtmus/svelte-fullpage/pull/62) about something else.
