### ISSUE TITLE
Is there a way to disable fullpage feature on mobile

### ISSUE THREAD

**Issue by xxibcill** [Hejtmus/svelte-fullpage#63]
I want to disable fullpage feature on mobile for a UI design reason

I try something like below code

```
{#if isMobile}
    <main class="scroll-container">
        <slot />
    </main>
{:else}
    <Fullpage bind:controller={fullpageController} class="scroll-container">
        <slot />
    </Fullpage>
{/if}
```

then it return this Error

```
TypeError: Cannot destructure property 'registerSection' of 'getContext(...)' as it is undefined.
```

are there a parameter to set to disable Fullpage

**Comment by Hejtmus** [comment]
Hey @xxibcill,

thanks for creating this issue and highlighting problem I totally oversaw. For now, there is not feature to selectively disable fullpage scrolling, but I will keep this issue open, to later implement it. I'm too busy to try to replicate your error, but I will try to use my author knowledge to help you fix this bug.

## What I suppose is error cause

I guess you are passing array of `<FullpageSection>` component instances as children to current component (first snippet you sent), that creates error (second snippet you sent), because `<FullpageSection>`  uses Svelte context API to get context to communicate with  `<Fullpage>`, thus it has to be child of `<Fullpage>` (indirect child is enough).

## Solution proposal

Don't include `<FullpageSection>` as `<main>` child.

### Principle of solution

#### Parent component

```svelte
{#if isMobile}
    <div>
        ...content
    </div>
{:else}
    <FullpageSection>
        <div>
            ...content
        </div>
    </FullpageSection>
{/if}
```

#### Current component

```svelte
{#if isMobile}
    <main class="scroll-container">
        <slot />
    </main>
{:else}
    <Fullpage bind:controller={fullpageController} class="scroll-container">
        <slot />
    </Fullpage>
{/if}
```

### Fullpage remover wrapper

Personally I would rather write some wrapper that conditionally uses `<FullpageSection>` and `<FullpageSlide>` when `<Fullpage>` is present.

```svelte
<script>
    export let isSlide = false
</script>

{#if isMobile}
        <slot />
{:else if isSlide}
    <FullpageSlide>
        <slot />
    </FullpageSlide>
{:else}
    <FullpageSection>
        <slot />
    </FullpageSection>
{/if}
```

Best regards,
Filip.

**Comment by xxibcill** [comment]
Hi @Hejtmus,
Thank you for responding to my issue. Now I can disable it on mobile. This is my workaround.

I create a `Section` component to replace `FullpageSection`

```svelte
<script lang="ts">
    import { FullpageSection, type FullpageExternalControllerStore } from 'svelte-fullpage'
    import { mediaStore } from '$lib/stores/mediaStore'
    import { fullpageStore } from '$lib/stores/fullPageStore'
    let isMobile: boolean

    mediaStore.subscribe((value) => {
        isMobile = value.isMobile
    })

    let fullpageController: FullpageExternalControllerStore | undefined

    fullpageStore.subscribe((value) => {
        fullpageController = value
    })

    let idd = ''
    export { idd as id }
</script>

{#if fullpageController && !isMobile}
    <FullpageSection id={idd} title={idd}>
        <slot />
    </FullpageSection>
{:else}
    <section id={idd} class={clazz}>
        <slot />
    </section>
{/if}
```

I check if fullpageController is exist before render FullpageSection to prevent `'getContext(...)' as it is undefined.`
but it work when enable csr not work with prerender mode

**Comment by Hejtmus** [comment]
If you need SSR with prerendering, probably the most easiest solution is to create 2 versions of your content, Fullpage version and non-Fullpage version. Then based client width, you will selectively show desired one with CSS. But his solution is basically ignoring this lib for small viewports. Example:

```
<Fullpage class="hidden md:block">
    {#each sections as section}
        <FullpageSection>
           ...sth
        </FullpageSection>
    {/each}
</Fullpage>
<div class="md:hidden block">
    {#each sections as section}
       ...sth
    {/each}
</div>
```

Note: I used Tailwindcss classes just to illustrate my idea.
